### ISSUE TITLE
i2c hangs on ACK from OLED

### ISSUE THREAD

**Issue by aaroneiche** [ADBeta/CH32Vxxx_lib_swi2c#1]
I'm trying to use this library to communicate with an SSD1306 OLED display, when trying to write to the display it gets stuck when releasing the SDA line to the target device for the ACK bit. 

I think the issue is happening in the RELEASE_SDA method - which I realize is just a `gpio_set_mode` call. It should be pretty straightforward, but I wondered if anyone had seen anything like this otherwise. I tracked it down just peppering the code with serial messages so I could see where it stopped.
```
	// Transmit bits MSB First
	uint8_t index = 8;
	while(index--)
	{
		// Transmit one bit at a time
		uint8_t bit = data & 0x80;
		if(bit) { RELEASE_SDA; } else { ASSERT_SDA; }

		wait();
	}
```
https://github.com/ADBeta/CH32V003_lib_swi2c/blob/49debdbe3a447816806e4a8c3c9370fd5353f2e3/lib_swi2c.c#L260

Right now I'm doing some simple testing seeing if I can just drive this display using the software library.

**Comment by ADBeta** [comment]
Thanks for letting me know. 
This projects stalled a bit due to lack of interest from the community, so I haven't looked that deeply into the bug of the software haha.

I would imaging the issue you're having is somewhere in the `clk_stretch` function. I'm currently a bit too busy to look into this, but feel free to dig into it and if you find out what the issue is, drop a message or a PR :)

In the meantime, I have this other project which uses the dedicated I2C Hardware to control the bus 
https://github.com/ADBeta/CH32V003_lib_i2c
This should be a lot less buggy, although I also need to go through this and update it and add an example.

**Comment by aaroneiche** [comment]
Thanks for responding! After having spent the day with it, I think I'm actually dealing with an ACK problem, though I don't know whether this is the fault of the display or the library. I'll keep poking at it.

**Comment by aaroneiche** [comment]
This appears to be user error. I'm still early in the process, but I was using the wrong address for my device. Device address is `0x78`. In most contexts I've had to send `0x3C` (which is `0x78` right-shifted by 1).  I think what other libraries do is take an address and left-shift in a read or write bit.

**Comment by Ashley-Bayliss** [comment]
I had chosen originally to use an 8bit address, which is common on an Arduino library I used a lot, but have since decided to change to a 7bit address. I haven't updated this codebase yet with that change but I can do if that would help you.

Apologies for the confusion, I was going on an assumption I had picked up from one place and hadn't looked into it haha. 
Let me know if you find any more issues, and if you would like this lib changing to a 7bit address type
